from intelgraph.core.playbook.models import (
    Playbook,
    PlaybookStep,
    StepActionType,
    TriggerCondition,
)

DEFAULT_PLAYBOOKS: list[Playbook] = [
    Playbook(
        playbook_id="c2_ip_detected",
        name="C2 IP Detected",
        description="A C2 server IP was detected. Block, analyse, and notify.",
        severity_level="high",
        entity_types=["ip_address"],
        trigger_conditions=TriggerCondition(
            alert_categories=["c2_detection", "threat_intel"],
            severities=["high", "critical"],
            entity_types=["ip_address"],
            confidence_min=0.7,
        ),
        steps=[
            PlaybookStep(
                "c2_block",
                StepActionType.BLOCK,
                "Block IP at firewall perimeter",
                automated=True,
                order=1,
            ),
            PlaybookStep(
                "c2_forensic",
                StepActionType.INVESTIGATE,
                "Perform forensic analysis on affected systems",
                automated=False,
                order=2,
            ),
            PlaybookStep(
                "c2_scan",
                StepActionType.SCAN,
                "Scan network for other systems communicating with this IP",
                automated=True,
                order=3,
            ),
            PlaybookStep(
                "c2_notify",
                StepActionType.NOTIFY,
                "Notify SOC team with full investigation report",
                automated=False,
                order=4,
            ),
        ],
    ),
    Playbook(
        playbook_id="high_risk_cve",
        name="High Risk CVE",
        description="A critical vulnerability was detected. Identify, patch, verify.",
        severity_level="high",
        entity_types=["cve"],
        trigger_conditions=TriggerCondition(
            alert_categories=["vulnerability", "cve"],
            severities=["high", "critical"],
            entity_types=["cve"],
            confidence_min=0.6,
        ),
        steps=[
            PlaybookStep(
                "cve_list",
                StepActionType.INVESTIGATE,
                "List all affected systems and software versions",
                automated=True,
                order=1,
            ),
            PlaybookStep(
                "cve_check_patch",
                StepActionType.INVESTIGATE,
                "Check patch availability and deployment status",
                automated=True,
                order=2,
            ),
            PlaybookStep(
                "cve_patch",
                StepActionType.PATCH,
                "Apply patch or implement vendor workaround",
                automated=False,
                order=3,
            ),
            PlaybookStep(
                "cve_verify",
                StepActionType.MONITOR,
                "Verify patch success and monitor for exploitation attempts",
                automated=True,
                order=4,
            ),
        ],
    ),
    Playbook(
        playbook_id="ransomware_cve",
        name="Ransomware CVE",
        description="A CVE associated with known ransomware campaigns was detected. Isolate, restore, report.",
        severity_level="critical",
        entity_types=["cve"],
        trigger_conditions=TriggerCondition(
            alert_categories=["vulnerability", "cve", "ransomware"],
            severities=["critical"],
            entity_types=["cve"],
            known_ransomware=True,
            confidence_min=0.5,
        ),
        steps=[
            PlaybookStep(
                "ransom_isolate",
                StepActionType.ISOLATE,
                "Immediately isolate affected systems from network",
                automated=True,
                order=1,
            ),
            PlaybookStep(
                "ransom_restore",
                StepActionType.RESTORE,
                "Restore from clean backup if available",
                automated=False,
                order=2,
            ),
            PlaybookStep(
                "ransom_ioc",
                StepActionType.NOTIFY,
                "Share IOCs with threat intelligence community",
                automated=True,
                order=3,
            ),
            PlaybookStep(
                "ransom_legal",
                StepActionType.NOTIFY,
                "File legal notification per regulatory requirements",
                automated=False,
                order=4,
            ),
        ],
    ),
    Playbook(
        playbook_id="malware_domain",
        name="Malware Domain",
        description="A domain associated with malware was detected. Sinkhole, clean, notify.",
        severity_level="high",
        entity_types=["domain"],
        trigger_conditions=TriggerCondition(
            alert_categories=["malware", "domain", "threat_intel"],
            severities=["high", "critical"],
            entity_types=["domain"],
            confidence_min=0.6,
        ),
        steps=[
            PlaybookStep(
                "domain_sinkhole",
                StepActionType.SINKHOLE,
                "Sinkhole domain via DNS redirect",
                automated=True,
                order=1,
            ),
            PlaybookStep(
                "domain_dns",
                StepActionType.INVESTIGATE,
                "Clear DNS cache and check for propagated records",
                automated=True,
                order=2,
            ),
            PlaybookStep(
                "domain_scan",
                StepActionType.SCAN,
                "Scan internal systems for domain communications",
                automated=True,
                order=3,
            ),
            PlaybookStep(
                "domain_notify",
                StepActionType.NOTIFY,
                "Notify affected users and IT team",
                automated=False,
                order=4,
            ),
        ],
    ),
]
