import copy
from pathlib import Path
from typing import Any

import yaml

DEFAULT_CONFIG_PATHS: list[Path] = [
    Path.cwd() / "intelgraph.yaml",
    Path.cwd() / "intelgraph.yml",
    Path.home() / ".config" / "intelgraph" / "intelgraph.yaml",
    Path.home() / ".intelgraph.yaml",
]

DEFAULT_CONFIG: dict[str, Any] = {
    "storage": {"backend": "sqlite", "path": "intelgraph.db", "pool_size": 5},
    "collectors": {"enabled": [], "timeout": 30, "retries": 3},
    "trust": {"min_trust_score": 0, "min_confidence_score": 0},
    "output": {"default_format": "json", "pretty": False},
    "jobs": {"max_workers": 4, "queue_size": 100},
    "deployment": {"profile": "development"},
    "cors": {"origins": []},
    "rate_limit": {
        "max_requests": 100,
        "window": 60,
        "per_user": True,
        "per_endpoint": True,
        "health": {"max_requests": 200, "window": 60},
        "auth": {"max_requests": 30, "window": 60},
        "read": {"max_requests": 100, "window": 60},
        "write": {"max_requests": 50, "window": 60},
    },
    "secret_key": "",
    "distributed": {"enabled": False},
    "task_queue": {"backend": "in_memory"},
    "worker": {"heartbeat_interval": 30},
    "api": {
        "read_auth_required": False,
        "feature_flags": {},
        "version": "v1",
    },
    "security": {
        "csp": "default-src 'self'",
        "hsts": True,
        "hsts_max_age": 31536000,
        "x_content_type_options": "nosniff",
        "x_frame_options": "DENY",
        "x_xss_protection": "1; mode=block",
        "cache_control": "no-store",
    },
    "logging": {
        "level": "INFO",
        "format": "structured",
        "file": "",
        "rotation": {
            "max_bytes": 10485760,
            "backup_count": 5,
        },
    },
    "alerting": {
        "enabled": False,
        "cooldown_seconds": 300,
        "webhook_url": "",
        "thresholds": {
            "error_rate": {"enabled": False, "max": 10, "severity": "warning"},
            "request_latency": {"enabled": False, "max_ms": 1000.0, "severity": "warning"},
            "rate_limit_hits": {"enabled": False, "max": 50, "severity": "warning"},
            "pagerank_convergence": {
                "enabled": False,
                "max_duration_ms": 10000.0,
                "severity": "warning",
            },
            "influence_computation_time": {
                "enabled": False,
                "max_duration_ms": 30000.0,
                "severity": "warning",
            },
            "influence_score_anomaly": {
                "enabled": False,
                "max_top_to_mean_ratio": 100.0,
                "severity": "warning",
            },
            "anomaly_spike": {"enabled": False, "max_high_count": 10, "severity": "warning"},
            "anomaly_critical_threshold": {
                "enabled": False,
                "min_anomaly_score": 0.9,
                "severity": "critical",
            },
            "anomaly_distribution_shift": {
                "enabled": False,
                "max_mean_score_change": 0.3,
                "severity": "warning",
            },
            "anomaly_cross_version_inconsistency": {
                "enabled": False,
                "max_score_deviation": 0.2,
                "severity": "warning",
            },
            "anomaly_baseline_drift_surge": {
                "enabled": False,
                "max_baseline_drift": 3.0,
                "severity": "warning",
            },
            "attack_path_high_risk": {
                "enabled": False,
                "max_risk_score": 0.8,
                "severity": "critical",
            },
            "attack_path_bottleneck_change": {
                "enabled": False,
                "max_bottleneck_frequency_change": 0.3,
                "severity": "warning",
            },
            "attack_path_surface_expansion": {
                "enabled": False,
                "max_surface_growth": 0.5,
                "severity": "warning",
            },
            "attack_path_inconsistency": {
                "enabled": False,
                "max_score_deviation": 0.2,
                "severity": "warning",
            },
            "causal_cascading_anomaly": {
                "enabled": False,
                "max_cascade_depth": 3,
                "severity": "warning",
            },
            "causal_multi_community_propagation": {
                "enabled": False,
                "max_community_span": 2,
                "severity": "warning",
            },
            "causal_influence_driven_spread": {
                "enabled": False,
                "max_influence_spread": 0.8,
                "severity": "warning",
            },
            "causal_confidence_threshold_breach": {
                "enabled": False,
                "min_root_cause_confidence": 0.5,
                "severity": "warning",
            },
            "prediction_risk_threshold_breach": {
                "enabled": False,
                "max_risk_score": 0.85,
                "severity": "critical",
            },
            "prediction_confidence_collapse": {
                "enabled": False,
                "min_confidence": 0.2,
                "severity": "warning",
            },
            "prediction_drift_breach": {"enabled": False, "max_drift": 0.3, "severity": "warning"},
            "prediction_model_degradation": {
                "enabled": False,
                "min_performance": 0.6,
                "severity": "warning",
            },
            "kernel_coherence_collapse": {
                "enabled": False,
                "min_coherence": 0.3,
                "severity": "critical",
            },
            "kernel_cross_model_disagreement": {
                "enabled": False,
                "max_disagreement": 0.4,
                "severity": "warning",
            },
            "safety_violation_detected": {
                "enabled": False,
                "max_violations": 5,
                "severity": "critical",
            },
            "governance_compliance_breach": {
                "enabled": False,
                "max_breaches": 3,
                "severity": "critical",
            },
            "nlp_extraction_failure_spike": {
                "enabled": False,
                "max_failure_rate": 0.2,
                "severity": "warning",
            },
            "nlp_model_load_failure": {
                "enabled": False,
                "max_load_failures": 3,
                "severity": "critical",
            },
            "nlp_link_accuracy_degradation": {
                "enabled": False,
                "min_accuracy": 0.5,
                "severity": "warning",
            },
            "nlp_classification_confidence_collapse": {
                "enabled": False,
                "min_confidence": 0.3,
                "severity": "warning",
            },
            "reasoning_divergence_detected": {
                "enabled": False,
                "max_divergence": 0.5,
                "severity": "warning",
            },
            "contradiction_explosion": {
                "enabled": False,
                "max_contradictions": 20,
                "severity": "critical",
            },
            "learning_loop_instability": {
                "enabled": False,
                "max_instability": 0.3,
                "severity": "warning",
            },
            "hypothesis_confidence_collapse": {
                "enabled": False,
                "min_confidence": 0.2,
                "severity": "warning",
            },
            "inference_drift_detected": {
                "enabled": False,
                "max_drift": 0.15,
                "severity": "warning",
            },
            "agent_deadlock_detected": {
                "enabled": False,
                "max_deadlocks": 5,
                "severity": "critical",
            },
            "agent_execution_failure_spike": {
                "enabled": False,
                "max_failure_rate": 0.3,
                "severity": "critical",
            },
            "agent_safety_violation_surge": {
                "enabled": False,
                "max_violations": 10,
                "severity": "critical",
            },
            "agent_kill_switch_engaged": {"enabled": False, "severity": "critical"},
            "agent_feedback_drift_detected": {
                "enabled": False,
                "max_drift": 0.2,
                "severity": "warning",
            },
            "agent_simulation_risk_breach": {
                "enabled": False,
                "max_risk": 0.8,
                "severity": "warning",
            },
            "agent_memory_corruption_detected": {
                "enabled": False,
                "max_corruption": 0.1,
                "severity": "critical",
            },
            "max_threat_score": {"enabled": True, "max": 75.0, "severity": "critical"},
        },
    },
    "backup": {
        "output_dir": "./backups",
        "pg_dump_path": "pg_dump",
    },
    "export": {
        "max_size_bytes": 104857600,
        "default_format": "graphml",
        "stream_chunk_size": 8192,
        "pretty": False,
    },
    "algorithms": {
        "default_mst": "kruskal",
        "default_heuristic": "zero",
        "max_path_nodes": 10000,
        "timeout_seconds": 30,
    },
    "datasources": {
        "max_poll_size": 10000,
        "default_poll_interval": 3600,
        "consecutive_failure_threshold": 3,
        "entity_match_threshold": 0.7,
        "incremental_sync": True,
    },
    "influence": {
        "pagerank_damping": 0.85,
        "pagerank_max_iterations": 100,
        "pagerank_tolerance": 1e-8,
        "propagation_default_threshold": 0.5,
        "propagation_default_decay": 0.5,
        "propagation_max_depth": 10,
        "composite_pr_weight": 0.5,
        "composite_degree_weight": 0.3,
        "composite_outbound_weight": 0.2,
    },
    "anomaly": {
        "zscore_threshold": 3.0,
        "community_zscore_threshold": 2.5,
        "temporal_deviation_threshold": 2.0,
        "multi_factor_weights": {
            "zscore": 0.20,
            "iqr": 0.15,
            "degree_outlier": 0.20,
            "temporal": 0.15,
            "community": 0.15,
            "influence": 0.15,
        },
        "baseline_history_size": 100,
        "top_n_default": 10,
        "max_top_n": 1000,
    },
    "attack_path": {
        "default_max_depth": 5,
        "max_paths_per_query": 100,
        "max_enumeration_depth": 10,
        "critical_node_sample_size": 20,
        "surface_max_depth": 4,
        "cache_enabled": True,
        "deterministic": True,
    },
    "reasoning": {
        "causal_max_depth": 5,
        "causal_max_causes": 10,
        "causal_max_paths": 100,
        "causal_decay_factor": 0.7,
        "causal_confidence_weight": 0.5,
        "causal_influence_weight": 0.3,
        "causal_temporal_weight": 0.2,
        "deterministic": True,
    },
    "prediction": {
        "default_horizon": 1,
        "short_horizon_steps": 1,
        "medium_horizon_steps": 3,
        "long_horizon_steps": 6,
        "ensemble_enabled": True,
        "counterfactual_enabled": True,
        "uncertainty_propagation": True,
        "deterministic": True,
        "model_health_interval": 300,
        "feature_ttl_seconds": 3600,
    },
    "kernel": {
        "deterministic": True,
        "enable_anomaly_phase": True,
        "enable_causal_phase": True,
        "enable_prediction_phase": True,
        "coherence_threshold": 0.5,
        "trace_logging": True,
        "failover_mode": "fallback_to_safe",
    },
    "explainability": {
        "enabled": True,
        "max_top_features": 5,
        "global_feature_limit": 10,
        "model_fidelity_weight": 0.3,
        "counterfactual_max_iterations": 100,
    },
    "safety": {
        "enabled": True,
        "global_min": 0.0,
        "global_max": 1.0,
        "strict_mode": False,
        "fallback_strategy": "constant",
        "fallback_default": 0.0,
        "bounds": {},
        "constraints": {},
    },
    "governance": {
        "enabled": True,
        "audit_max_entries": 10000,
        "auto_approve_low_risk": True,
        "risk_threshold": 0.7,
        "compliance_rules": {},
        "policies": {},
    },
    "connectors": {
        "default_timeout": 30.0,
        "default_retry_attempts": 3,
        "default_rate_limit_quota": 100,
        "default_rate_limit_burst": 20,
        "dlq_max_size": 10000,
        "heartbeat_interval": 30.0,
        "circuit_breaker_threshold": 5,
        "circuit_breaker_reset": 60.0,
        "sandbox_level": "medium",
        "zero_trust": True,
        "supply_chain_validation": False,
    },
    "ingestion": {
        "default_batch_size": 100,
        "max_queue_size": 10000,
        "trust_decay_half_life_days": 30.0,
        "dedup_enabled": True,
        "poison_filter_enabled": True,
        "replay_max_events": 100000,
        "late_event_max_lateness": 300.0,
        "idempotency_ttl": 3600,
    },
    "streaming": {
        "delivery_mode": "at_least_once",
        "max_events_per_topic": 100000,
        "backpressure_max_queue": 10000,
        "partitions": 4,
    },
    "security": {
        "payload_signing": True,
        "anomaly_detection_enabled": True,
        "sandbox_escape_prevention": True,
        "runtime_policy_enforcement": True,
        "abac_enabled": True,
    },
    "multitenant": {
        "enabled": True,
        "default_tenant": "default",
        "quota_max_sources": 10,
        "quota_max_ingestion_rate": 1000,
        "quota_max_storage_mb": 1024,
    },
    "cost_control": {
        "budget": 1000.0,
        "cost_tracking_enabled": True,
        "budget_aware_throttling": True,
        "roi_tracking": True,
        "auto_disable_roi_threshold": -0.5,
    },
    "compliance": {
        "gdpr_enabled": True,
        "data_residency_enabled": True,
        "retention_enabled": True,
        "legal_hold_enabled": True,
        "compliance_scoring": True,
        "sovereignty_enforcement": True,
    },
    "decision": {
        "risk_threshold": 0.7,
        "auto_mitigation": True,
        "human_in_the_loop": True,
        "max_escalation_level": 3,
        "playbook_execution": True,
    },
    "quality": {
        "eiqs_enabled": True,
        "source_reliability_tracking": True,
        "cross_source_consistency": True,
        "temporal_decay_enabled": True,
        "confidence_calibration": True,
        "hallucination_detection": True,
        "ground_truth_feedback": True,
    },
    "resilience": {
        "failure_correlation_enabled": True,
        "global_retry_max": 5,
        "blast_radius": 3,
        "auto_fallback": True,
        "degraded_mode": True,
        "disaster_recovery": True,
    },
    "nlp": {
        "enabled": True,
        "default_ner_engine": "rule_based",
        "default_rel_engine": "rule_based",
        "default_event_engine": "rule_based",
        "default_classifier": "rule_based",
        "default_summarizer": "rule_based",
        "max_text_length": 1000000,
        "max_summary_sentences": 5,
        "link_to_graph_enabled": True,
    },
    "nlp_economics": {
        "budget_limit": 1000.0,
        "min_roi": 0.5,
        "cost_aware_routing": True,
        "model_efficiency_weight": 0.7,
        "compute_waste_tracking": True,
    },
    "cognitive": {
        "enabled": True,
        "reasoning_max_depth": 5,
        "min_confidence": 0.1,
        "contradiction_confidence_threshold": 0.5,
        "max_hypotheses": 50,
        "learning_rate": 0.1,
        "max_traces": 10000,
        "optimization_history_size": 1000,
        "scenario_templates": [
            "command_and_control",
            "data_exfiltration",
            "lateral_movement",
            "privilege_escalation",
            "persistence",
            "defense_evasion",
            "initial_access",
            "impact",
        ],
    },
    "agent": {
        "enabled": True,
        "max_agents": 10,
        "default_sandbox": "medium",
        "heartbeat_interval": 30.0,
        "forbidden_actions": ["shutdown", "destroy", "nuke"],
        "deadlock_timeout": 60.0,
        "conflict_resolution": "priority",
    },
    "agent_execution": {
        "max_retries": 3,
        "retry_base_delay": 1.0,
        "retry_max_delay": 60.0,
        "simulate_before_execute": True,
        "audit_enabled": True,
        "feedback_learning": True,
        "compiler_min_confidence": 0.3,
        "tool_default_timeout": 30.0,
    },
    "agent_safety": {
        "human_in_loop": True,
        "self_protection": True,
        "max_risk_score": 0.9,
        "sandbox_enabled": True,
        "anomaly_detection": True,
        "auto_rollback_on_anomaly": True,
        "dynamic_approval_thresholds": True,
    },
    "agent_simulation": {
        "chaos_enabled": True,
        "propagation_max_depth": 3,
        "safe_mode_risk_threshold": 0.7,
        "failure_rates": {
            "network": 0.1,
            "timeout": 0.05,
            "malformed": 0.05,
            "crash": 0.02,
            "corruption": 0.03,
        },
    },
    "agent_distributed": {
        "enabled": False,
        "node_timeout": 30.0,
        "heartbeat_interval": 15.0,
        "max_retries": 3,
        "load_balancing": "round_robin",
        "state_sync_interval": 5.0,
    },
    "metaintel": {
        "enabled": True,
        "governance_check_interval": 60,
        "diagnostics_history_size": 1000,
        "policy_auto_refine": True,
        "meta_reasoning_enabled": True,
        "optimization_auto_approve_low_risk": True,
        "architecture_mutation_safe_mode": True,
        "truth_snapshot_interval": 300,
        "identity_consistency_enforcement": True,
        "alignment_check_enabled": True,
        "safety_meta_monitoring": True,
        "observability_snapshot_interval": 60,
        "alerting_cooldown_seconds": 300,
        "state_versioning_enabled": True,
    },
    "ucos": {
        "enabled": True,
        "unified_reasoning": True,
        "unified_execution": True,
        "unified_policy": True,
        "unified_truth": True,
        "closed_loop_enabled": True,
        "consolidation_auto_scan": True,
        "simplification_enforcement": True,
        "safety_kill_switch_enabled": True,
        "dependency_validation": True,
        "meta_control_approval_gate": True,
        "unified_alerting_cooldown": 60,
        "stop_on_execution_failure": True,
    },
    "metaintel_alerting": {
        "reasoning_collapse": {
            "enabled": False,
            "max": 0.3,
            "severity": "critical",
            "layers": ["reasoning"],
            "metric_key": "reasoning_quality",
        },
        "cross_phase_inconsistency": {
            "enabled": False,
            "max": 0.5,
            "severity": "critical",
            "layers": ["metaintel"],
            "metric_key": "cross_phase_alignment",
        },
        "execution_reasoning_mismatch": {
            "enabled": False,
            "max": 0.4,
            "severity": "high",
            "layers": ["reasoning", "execution"],
            "metric_key": "execution_reliability",
        },
        "knowledge_corruption": {
            "enabled": False,
            "max": 0.3,
            "severity": "critical",
            "layers": ["nlp"],
            "metric_key": "knowledge_consistency",
        },
        "policy_conflict_explosion": {
            "enabled": False,
            "max": 10,
            "severity": "critical",
            "layers": ["governance"],
            "metric_key": "governance_conflict_rate",
        },
        "autonomous_instability": {
            "enabled": False,
            "max": 0.4,
            "severity": "critical",
            "layers": ["metaintel"],
            "metric_key": "stability_index",
        },
        "global_drift_exceeded": {
            "enabled": False,
            "max": 0.3,
            "severity": "high",
            "layers": ["metaintel"],
            "metric_key": "system_drift",
        },
        "architecture_divergence": {
            "enabled": False,
            "max": 0.5,
            "severity": "high",
            "layers": ["metaintel"],
            "metric_key": "architecture_mutation_rate",
        },
    },
    "ucos_alerting": {
        "duplicate_engine_detected": {
            "enabled": False,
            "max": 0,
            "severity": "critical",
            "metric_key": "ucos_duplicates_found",
        },
        "reasoning_divergence": {
            "enabled": False,
            "max": 0.3,
            "severity": "high",
            "metric_key": "ucos_reasoning_confidence",
        },
        "execution_inconsistency": {
            "enabled": False,
            "max": 0.3,
            "severity": "critical",
            "metric_key": "ucos_execution_success",
        },
        "governance_conflict": {
            "enabled": False,
            "max": 5,
            "severity": "high",
            "metric_key": "ucos_policy_conflicts",
        },
        "system_complexity_growth": {
            "enabled": False,
            "max": 0.8,
            "severity": "warning",
            "metric_key": "ucos_complexity_index",
        },
        "uncontrolled_self_modification": {
            "enabled": False,
            "max": 0,
            "severity": "critical",
            "metric_key": "ucos_unauthorized_changes",
        },
    },
}


def load_config(path: str | None = None) -> dict[str, Any]:
    cfg: dict[str, Any] = {}
    cfg.update(copy.deepcopy(DEFAULT_CONFIG))

    if path:
        config_paths = [Path(path)]
    else:
        config_paths = DEFAULT_CONFIG_PATHS

    for config_path in config_paths:
        if config_path.exists():
            with open(config_path) as f:
                loaded = yaml.safe_load(f)
            if loaded and isinstance(loaded, dict):
                _deep_merge(cfg, loaded)
            break

    return cfg


def _deep_merge(base: dict, overlay: dict) -> None:
    for key, value in overlay.items():
        if key in base and isinstance(base[key], dict) and isinstance(value, dict):
            _deep_merge(base[key], value)
        else:
            base[key] = value
