# ── Human Review Engine Constants ──
APPROVED_CONFIDENCE_BOOST: float = 5.0
APPROVED_CONTRADICTION_REDUCTION: float = 10.0
REJECTED_CONFIDENCE_PENALTY: float = 10.0
REJECTED_CONTRADICTION_INCREASE: float = 5.0
NEEDS_MORE_NO_CHANGE: float = 0.0

# ── Verification Manager Review Boost (must match ReviewEngine values) ──
HUMAN_REVIEW_APPROVED_BOOST: float = APPROVED_CONFIDENCE_BOOST
HUMAN_REVIEW_REJECTED_PENALTY: float = REJECTED_CONFIDENCE_PENALTY

# ── Evidence Chain Confidence Thresholds ──
CONSENSUS_AGREEMENT_RATIO: float = 0.7
CONTRADICTION_RATIO_THRESHOLD: float = 0.3
DEFAULT_SOURCE_TRUST: int = 50
